// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi1aIrahPgZMbcvb-oPNGJvgpr4pFKTuE',
    appId: '1:144699971978:web:6b90285b39618d927bd073',
    messagingSenderId: '144699971978',
    projectId: 'myproject-b85c4',
    authDomain: 'myproject-b85c4.firebaseapp.com',
    storageBucket: 'myproject-b85c4.appspot.com',
    measurementId: 'G-XG878T87ZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHNj9uOWBGXMnfZ635DgO80f1X86O-jnI',
    appId: '1:144699971978:android:911337cf7cf8f1727bd073',
    messagingSenderId: '144699971978',
    projectId: 'myproject-b85c4',
    storageBucket: 'myproject-b85c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBYyWWr6NLs-jZm7I2EvWZt_1rw5vekSI',
    appId: '1:144699971978:ios:5944c55f443d2f777bd073',
    messagingSenderId: '144699971978',
    projectId: 'myproject-b85c4',
    storageBucket: 'myproject-b85c4.appspot.com',
    iosBundleId: 'com.example.firebaseauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBYyWWr6NLs-jZm7I2EvWZt_1rw5vekSI',
    appId: '1:144699971978:ios:35d6523a2317d0977bd073',
    messagingSenderId: '144699971978',
    projectId: 'myproject-b85c4',
    storageBucket: 'myproject-b85c4.appspot.com',
    iosBundleId: 'com.example.firebaseauth.RunnerTests',
  );
}
